# Plot histogram and publish to plotly
# Plot four different histograms in one figure with four subfigures and publish to plotly
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
import plotly.plotly as py
exec(open("C:\Pw\plotly_pw.txt").read())
gaussian_numbers = np.random.randn(1000)
gaussian_numbers_2=np.random.randn(1000)
fig=plt.figure(1,figsize=(15, 15))
plt.hist(gaussian_numbers)
plt.title("Gaussian Histogram")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.grid(True)
#
fig = plt.gcf()
py.sign_in(plotly_login, plotly_token)
plot_url = py.plot_mpl(fig, filename='histogram0.py')
plt.figure()
fig2=plt.figure(2,figsize=(15, 15))
plt.tight_layout()
plt.subplot(221)
plt.hist(gaussian_numbers)
plt.title("Gaussian Histogram")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.grid(True)
plt.subplot(222)
plt.hist(gaussian_numbers, orientation='horizontal',color='red')
plt.title("Gaussian Histogram")
plt.xlabel("Frequency")
plt.ylabel("Value")
plt.grid(True)
# plt.show()
plt.subplot(223)
plt.hist([gaussian_numbers,gaussian_numbers_2])
plt.title('Histogram for two Gaussian Distribution')
plt.xlabel("Values")
plt.ylabel("Frequency")
plt.grid(True)
# plt.show()
plt.subplot(224)
plt.title('Histogram for sum of two Gaussian Distribution')
plt.xlabel("Values")
plt.ylabel("Frequency")
plt.hist([gaussian_numbers,gaussian_numbers_2],15, stacked=True, normed = False,rwidth=0.9)
plt.grid(True)
plt.show()
plot_url = py.plot_mpl(fig2, filename='histogram1.py')
